"""
report.py
---------

Generates a DNA analysis report.

Author: Roshni Kathiresan
Project: GeneInsight
Version: 1.0
"""

def generate_report(sequence,
                    counts,
                    gc_content,
                    reverse,
                    rna,
                    protein,
                    orf,
                    restriction_sites,
                    filename="output/report.txt"):
    """
    Saves the DNA analysis report to a text file.
    """

    import os

    os.makedirs("output", exist_ok=True)

    with open(filename, "w") as file:

        file.write("="*60 + "\n")
        file.write("GENEINSIGHT DNA ANALYSIS REPORT\n")
        file.write("="*60 + "\n\n")

        file.write(f"Original DNA : {sequence}\n\n")

        file.write("Nucleotide Counts\n")
        file.write("-------------------------\n")

        for base, count in counts.items():
            file.write(f"{base} : {count}\n")

        file.write(f"\nGC Content : {gc_content}%\n")

        file.write(f"\nReverse Complement : {reverse}\n")

        file.write(f"\nRNA Sequence : {rna}\n")

        file.write(f"\nProtein Sequence : {protein}\n")

        file.write(f"\nFirst ORF : {orf}\n\n")

        file.write("Restriction Sites\n")
        file.write("-------------------------\n")

        for enzyme, positions in restriction_sites.items():

            if positions:
                file.write(f"{enzyme}: {positions}\n")
            else:
                file.write(f"{enzyme}: Not Found\n")

        file.write("\n")
        file.write("="*60 + "\n")
        file.write("Generated by GeneInsight\n")